#!/bin/sh
export APP_HOME="{{pkg.path}}"
export APP_DATA="{{pkg.svc_data_path}}"

export GEM_HOME="${APP_HOME}/dist/vendor/bundle/ruby/2.3.0"
export GEM_PATH="$(hab pkg path core/ruby)/lib/ruby/gems/2.3.0:$(hab pkg path core/bundler):$GEM_HOME"

export PATH="$PATH:${APP_HOME}/dist/bin"

exec 2>&1
exec chpst -u hab rackup -o 127.0.0.1 -p 9292
