version: '3'

services:
  wordpress:
    image: starkandwayne/wordpress:edge
    command: "start starkandwayne/wordpress --peer database --bind database:mysql.wordpress"
    links:
      - database
    volumes:
      - data-volume:/hab/svc/wordpress/data
    ports:
      - "8080:80"
  database:
    image: starkandwayne/mysql:edge
    command: "start starkandwayne/mysql --group wordpress"
    environment:
      HAB_MYSQL: |
        app_username='wordpress'
        app_password='wordpress'
        bind='0.0.0.0'
    ports:
      - "9631:9631"
volumes:
  data-volume: {}
